export const ariaLabel = { "aria-label": "description" };

export const QuestionsData = [
  {
    id: 1,
    name: "Мемы за 300",
    questions: [
      {
        id: 1,
        text: 100,
        answered: false,
        question: "Что должно быть написано?",
        image: "static/images/questions/1_1_question.jpg",
        answer_image: "static/images/questions/1_1_answer.jpg",
        answers: [
          { text: "Отсоси у тракториста", value: false },
          { text: "Скажи 300", value: true },
          { text: "Мы пришли с миром", value: false },
          { text: "Укуси мой блестящий металлический зад", value: false },
        ],
      },
      {
        id: 2,
        text: 200,
        answered: false,
        question: "Что должно быть написано?",
        image: "static/images/questions/1_2_question.jpg",
        answer_image: "static/images/questions/1_2_answer.jpg",
        answers: [
          { text: "Пива", value: false },
          { text: "Чипсеки", value: true },
          { text: "КЕК", value: false },
          { text: "Когда кто-то сказал 200", value: false },
        ],
      },
      {
        id: 3,
        text: 300,
        question: "Что он говорит?",
        image: "static/images/questions/1_3_question.jpg",
        answer_image: "static/images/questions/1_3_answer.jpg",
        answered: false,
        answers: [
          { text: "Простите", value: false },
          { text: "Хто я?", value: true },
          { text: "Кто я?", value: false },
          { text: "Шутке", value: false },
        ],
      },
      {
        id: 4,
        text: 400,
        question: "Род деятельности этого немолодого человека?",
        image: "static/images/questions/1_4_question.jpg",
        answer_image: "static/images/questions/1_4_answer.jpg",
        answered: false,
        answers: [
          { text: "Ученый", value: false },
          { text: "Своего рода ученый", value: true },
          { text: "Розбийник", value: false },
          { text: "Гоблин", value: false },
        ],
      },
      {
        id: 5,
        text: 500,
        question: "Что говорит пиня?",
        image: "static/images/questions/1_5_question.jpg",
        answer_image: "static/images/questions/1_5_answer.jpg",
        answered: false,
        answers: [
          { text: "Огонь", value: false },
          { text: "Изивинити", value: false },
          { text: "Спасибо", value: false },
          { text: "Ебать, спасибо нахуй", value: true },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Жиза",
    questions: [
      {
        id: 6,
        text: 100,
        question: "Как ощущает себя котик?",
        image: "static/images/questions/2_1_question.jpg",
        answer_image: "static/images/questions/2_1_answer.jpg",
        answered: false,
        answers: [
          { text: "Стлесс", value: true },
          { text: "Жесть", value: false },
          { text: "Страшн", value: false },
          { text: "В шоке", value: false },
        ],
      },
      {
        id: 7,
        text: 200,
        question: "Что отвечает этот красивый мужчина?",
        image: "static/images/questions/2_2_question.jpg",
        answer_image: "static/images/questions/2_2_answer.jpg",
        answered: false,
        answers: [
          { text: "Да", value: false },
          { text: "За дело", value: false },
          { text: "Работа не волк, в лес не убежит", value: false },
          { text: "Угу", value: true },
        ],
      },
      {
        id: 8,
        text: 300,
        question: "Что должно быть написано?",
        image: "static/images/questions/2_3_question.jpg",
        answer_image: "static/images/questions/2_3_answer.jpg",
        answered: false,
        answers: [
          { text: "Ну да, ну да, пошел я нахер", value: true },
          { text: "А про меня забыли", value: false },
          { text: "Ну да, ну да", value: false },
          { text: "Ох уж этот Билл, батьку не послушал", value: false },
        ],
      },
      {
        id: 9,
        text: 400,
        question: "Что говорит Киану?",
        image: "static/images/questions/2_4_question.jpg",
        answer_image: "static/images/questions/2_4_answer.jpg",
        answered: false,
        answers: [
          { text: "Ты супер", value: true },
          { text: "Ты превосходная", value: true },
          { text: "Ты молодец", value: true },
          { text: "Ты потрясающий", value: true },
        ],
      },
      {
        id: 10,
        text: 500,
        question: "Знаменитая фраза шкипера",
        image: "static/images/questions/2_5_question.jpg",
        answer_image: "static/images/questions/2_5_answer.jpg",
        answered: false,
        answers: [
          { text: "Приказываю кататься на пузе", value: false },
          { text: "Ковальски, анализ", value: true },
          { text: "Разбудить свои вкусовые рецепторы", value: false },
          { text: "Бежим за ним в стиле хомячков в шарах!", value: false },
        ],
      },
    ],
  },
  {
    id: 3,
    name: "чзхб",
    questions: [
      {
        id: 11,
        text: 100,
        answered: false,
        question: "Что он говорит?",
        image: "static/images/questions/3_1_question.jpg",
        answer_image: "static/images/questions/3_1_answer.jpg",
        answers: [
          { text: "Сосну?", value: false },
          { text: "Будем?", value: false },
          { text: "Держи", value: true },
          { text: "И зачем она мне?", value: false },
        ],
      },
      {
        id: 12,
        text: 200,
        question: "Что должно быть написано?",
        image: "static/images/questions/3_2_question.jpg",
        answer_image: "static/images/questions/3_2_answer.jpg",
        answered: false,
        answers: [
          { text: "До созвона", value: false },
          { text: "До связи", value: true },
          { text: "Позвони мне", value: false },
          { text: "А телефон где?", value: false },
        ],
      },
      {
        id: 13,
        text: 300,
        question: "Что всегда отвечает этот молодой человек?",
        image: "static/images/questions/3_3_question.jpg",
        answer_image: "static/images/questions/3_3_answer.jpg",
        answered: false,
        answers: [
          { text: "Да", value: true },
          { text: "Нета", value: false },
          { text: "Yes", value: false },
          { text: "Nope", value: false },
        ],
      },
      {
        id: 14,
        text: 400,
        question: "Знаменитая надпись на футболке",
        image: "static/images/questions/3_4_question.jpg",
        answer_image: "static/images/questions/3_4_answer.jpg",
        answered: false,
        answers: [
          { text: "Без женщин", value: false },
          { text: "Без девушек", value: false },
          { text: "Без баб", value: true },
          { text: "Без детей", value: false },
        ],
      },
      {
        id: 15,
        text: 500,
        question: "Что должно быть написано?",
        image: "static/images/questions/3_5_question.jpg",
        answer_image: "static/images/questions/3_5_answer.jpg",
        answered: false,
        answers: [
          { text: "Математика, есть математика", value: true },
          { text: "Физика, есть физика", value: false },
          { text: "Умножение, есть умножение", value: false },
          { text: "Еда, есть еда", value: false },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "нсбтвм",
    questions: [
      {
        id: 16,
        text: 100,
        question: "Как зовут мишку?",
        image: "static/images/questions/4_1_question.jpg",
        answer_image: "static/images/questions/4_1_answer.jpg",
        answered: false,
        answers: [
          { text: "Пидобир", value: true },
          { text: "Дядя федя", value: false },
          { text: "Любитель маленьких людей", value: false },
          { text: "Неверный вариант", value: false },
        ],
      },
      {
        id: 17,
        text: 200,
        question: "Что должно быть написано?",
        image: "static/images/questions/4_2_question.jpg",
        answer_image: "static/images/questions/4_2_answer.jpg",
        answered: false,
        answers: [
          { text: "Беда", value: false },
          { text: "Бунд", value: true },
          { text: "Война", value: false },
          { text: "Палка", value: false },
        ],
      },
      {
        id: 18,
        text: 300,
        question: "Что должно быть написано?",
        image: "static/images/questions/4_3_question.jpg",
        answer_image: "static/images/questions/4_3_answer.jpg",
        answered: false,
        answers: [
          { text: "Еда", value: false },
          { text: "Кушать", value: false },
          { text: "Кушац", value: true },
          { text: "А я тебя тут жду", value: false },
        ],
      },
      {
        id: 19,
        text: 400,
        question: "Какое прозвище у этого человека?",
        image: "static/images/questions/4_4_question.jpg",
        answer_image: "static/images/questions/4_4_answer.jpg",
        answered: false,
        answers: [
          { text: "Зубенко", value: false },
          { text: "Михаил", value: false },
          { text: "Петрович", value: false },
          { text: "Мафиозник", value: true },
        ],
      },
      {
        id: 20,
        text: 500,
        question: "Что должно быть написано?",
        image: "static/images/questions/4_5_question.jpg",
        answer_image: "static/images/questions/4_5_answer.jpg",
        answered: false,
        answers: [
          { text: "Друг друга", value: true },
          { text: "буй друга", value: false },
          { text: "Подругу", value: false },
          { text: "у друга", value: false },
        ],
      },
    ],
  },
  {
    id: 5,
    name: "Get a luck",
    questions: [
      {
        id: 21,
        text: 100,
        question: "Где?",
        image: "Картинки нет",
        answer_image: "Картинки нет",
        answered: false,
        answers: [
          { text: "Тут", value: true },
          { text: "Или тут", value: true },
          { text: "Или все же тут", value: false },
          { text: "Тутa", value: true },
        ],
      },
      {
        id: 22,
        text: 200,
        question: "Где?",
        image: "Картинки нет",
        answer_image: "Картинки нет",
        answered: false,
        answers: [
          { text: "Тут", value: false },
          { text: "Или тут", value: true },
          { text: "Или все же тут", value: true },
          { text: "Тутa", value: true },
        ],
      },
      {
        id: 23,
        text: 300,
        question: "Где?",
        image: "Картинки нет",
        answer_image: "Картинки нет",
        answered: false,
        answers: [
          { text: "Тут", value: true },
          { text: "Или тут", value: true },
          { text: "Или все же тут", value: true },
          { text: "Тутa", value: false },
        ],
      },
      {
        id: 24,
        text: 400,
        question: "Где?",
        image: "Картинки нет",
        answer_image: "Картинки нет",
        answered: false,
        answers: [
          { text: "Тут", value: false },
          { text: "Или тут", value: true },
          { text: "Или все же тут", value: true },
          { text: "Тутa", value: true },
        ],
      },
      {
        id: 25,
        text: 500,
        question: "Где?",
        image: "Картинки нет",
        answer_image: "Картинки нет",
        answered: false,
        answers: [
          { text: "Тут", value: true },
          { text: "Или тут", value: false },
          { text: "Или все же тут", value: true },
          { text: "Тутa", value: true },
        ],
      },
    ],
  },
];
